apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-mysql-cluster-0
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ""   # MUST be empty to match PVC
  local:
    path: /data/my-mysql-cluster-0
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - workerserver

